AcunmedyaAkademiPortfolio/Controllers/AdminLayoutController.cs
using System.Web.Mvc;

namespace AcunmedyaAkademiPortfolio.Controllers
{
    public class AdminLayoutController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult PartialHead()
        {
            return PartialView();
        }
        public PartialViewResult PartialNavbar()
        {
            return PartialView();
        }
        public PartialViewResult PartialScripts()
        {
            return PartialView();
        }
    }
}

AcunmedyaAkademiPortfolio/Views/AdminLayout/Index.cshtml
@{
    Layout = null;
}

<!doctype html>
<html lang="en">

<body>

    @Html.Action("PartialHead", "AdminLayout")


    <div class="wrapper d-flex align-items-stretch">

        @Html.Action("PartialNavbar", "AdminLayout")
        <!-- Page Content  -->
        <div id="content" class="p-4 p-md-5 pt-5">

            @RenderBody()

        </div>
    </div>

    @Html.Action("PartialScripts", "AdminLayout")
</body>
</html>

AcunmedyaAkademiPortfolio/Views/AdminLayout/PartialHead.cshtml
<head>
    <title>Portfolio Admin Panel</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/sidebar-02/css/style.css">
</head>

AcunmedyaAkademiPortfolio/Views/AdminLayout/PartialNavbar.cshtml
<nav id="sidebar">
    <div class="custom-menu">
        <button type="button" id="sidebarCollapse" class="btn btn-primary">
            <i class="fa fa-bars"></i>
            <span class="sr-only">Toggle Menu</span>
        </button>
    </div>

    <div class="p-4 pt-5">
        <h1><a href="/About/Index/" class="logo">Emir</a></h1>
        <ul class="list-unstyled components mb-5">

            <li><a href="/Default/Index"><i class="fa fa-home"></i> Siteye Git</a></li>
            <li><a href="/About/Index/"><i class="fa fa-user"></i>   Hakkımda</a></li>
            <li><a href="/Category/Index/"><i class="fa fa-th"></i> Kategoriler</a></li>
            <li><a href="/Education/Index/"><i class="fa fa-graduation-cap"></i> Eğitim Hayatım</a></li>
            <li><a href="/Experience/Index/"><i class="fa fa-briefcase"></i> Deneyimlerim</a></li>
            <li><a href="/Skill/Index/"><i class="fa fa-cogs"></i> Yeteneklerim</a></li>
            <li><a href="/Service/Index/"><i class="fa fa-wrench"></i> Hizmetlerim</a></li>
            <li><a href="/Message/Index/"><i class="fa fa-envelope"></i> Gelen Mesajlar</a></li>
            <li><a href="/SocialMedia/Index/"><i class="fa fa-share-alt"></i> Sosyal Medya</a></li>
            <li><a href="/Portfolio/Index/"><i class="fa fa-folder"></i> Projelerim</a></li>
            <li><a href="/Testimonial/Index/"><i class="fa fa-comment"></i> Referanslarım</a></li>
            @*<li><a href="/Statistic/Index/"><i class="fa fa-chart-bar"></i> İstatistikler</a></li>*@


        </ul>

        <div class="mb-5">
            <h3 class="h6">Bültene Abone Ol</h3>
            <form action="#" class="colorlib-subscribe-form">
                <div class="form-group d-flex">
                    <div class="icon"><span class="icon-paper-plane"></span></div>
                    <input type="text" class="form-control" placeholder="E-posta Adresinizi Girin">
                </div>
            </form>
        </div>

        <div class="footer">
            <p>
                Copyright &copy;
                <script>document.write(new Date().getFullYear());</script> Tüm haklar saklıdır.
            </p>
        </div>

    </div>
</nav>

AcunmedyaAkademiPortfolio/Views/AdminLayout/PartialScripts.cshtml
<script src="/sidebar-02/js/jquery.min.js"></script>
<script src="/sidebar-02/js/popper.js"></script>
<script src="/sidebar-02/js/bootstrap.min.js"></script>
<script src="/sidebar-02/js/main.js"></script>